"""SQLite interaction-state store.

IMPORTANT boundary: the markdown vault holds *knowledge* (the source of truth,
owned by Obsidian). This database holds only *interaction state* — sessions,
flashcard schedules, analytics, progress. It is disposable and never the
authority on knowledge. One DB, one server → every device sees the same state
(this is what makes cross-device sync trivial).
"""
from __future__ import annotations

import datetime as dt
from typing import Optional

from sqlmodel import Field, SQLModel, Session as DBSession, create_engine

import config


def now() -> dt.datetime:
    return dt.datetime.now(dt.timezone.utc)


class StudySession(SQLModel, table=True):
    id: str = Field(primary_key=True)
    created_at: dt.datetime = Field(default_factory=now)
    last_active: dt.datetime = Field(default_factory=now)
    topic_area: str = ""
    vault_context: str = ""          # context fetched once per session
    context_query: str = ""          # the query the context was built for (topic-shift detection)


class Message(SQLModel, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
    session_id: str = Field(index=True)
    role: str                         # "user" | "assistant"
    content: str
    pages_used: str = ""              # JSON list of page names
    backend: str = ""                 # which LLM answered
    created_at: dt.datetime = Field(default_factory=now)


class Flashcard(SQLModel, table=True):
    """One Active-Recall question under SM-2 scheduling."""
    id: Optional[int] = Field(default=None, primary_key=True)
    page: str = Field(index=True)     # source page name (stem)
    area: str = ""
    question: str = ""
    answer: str = ""
    qhash: str = Field(index=True)    # sha1(page + question) — dedupe key
    # SM-2 state
    ease: float = 2.5
    interval_days: int = 0
    repetitions: int = 0
    lapses: int = 0
    due: dt.datetime = Field(default_factory=now)
    last_reviewed: Optional[dt.datetime] = None
    suspended: bool = False
    deep_explanation: str = ""        # M8: on-demand Claude "why", generated by button


class PageStat(SQLModel, table=True):
    page: str = Field(primary_key=True)
    retrieved_count: int = 0
    promoted_count: int = 0
    answer_primary_count: int = 0     # times it was the top retrieved page
    last_retrieved: Optional[dt.datetime] = None


class QueryLog(SQLModel, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
    question: str = ""
    pages_retrieved: str = ""         # JSON list
    backend: str = ""
    promoted: bool = False
    session_id: str = ""
    created_at: dt.datetime = Field(default_factory=now)


class Progress(SQLModel, table=True):
    """Free-form key/value for streaks, counters, last-study-date, etc."""
    key: str = Field(primary_key=True)
    value: str = ""
    updated_at: dt.datetime = Field(default_factory=now)


class TokenUsage(SQLModel, table=True):
    """One paid LLM call's token usage + computed cost (Claude spend tracking)."""
    id: Optional[int] = Field(default=None, primary_key=True)
    backend: str = ""
    model: str = ""
    role: str = ""                  # "promote" | "ask"
    input_tokens: int = 0
    output_tokens: int = 0
    cache_write_tokens: int = 0
    cache_read_tokens: int = 0
    cost_usd: float = 0.0
    created_at: dt.datetime = Field(default_factory=now)


class Promotion(SQLModel, table=True):
    """A page created/extended via the compiler — drives recent-promoted + stats."""
    id: Optional[int] = Field(default=None, primary_key=True)
    page: str = ""
    title: str = ""
    area: str = ""
    decision: str = ""              # CREATE | EXTEND
    created_at: dt.datetime = Field(default_factory=now)


class ReviewItem(SQLModel, table=True):
    """A proposed vault change awaiting human approval — the review queue.

    Fed by three sources (kind): 'ingest' (a dropped PDF), 'gap' (a planned page
    that doesn't exist), 'status-fill' (a mature page missing a required section).
    Lifecycle: suggested → (draft) → pending → applied | rejected.
    """
    id: Optional[int] = Field(default=None, primary_key=True)
    kind: str = ""                  # ingest | gap | status-fill
    source: str = ""                # filename / "audit" / topic
    title: str = ""                 # page name or topic (display)
    area: str = ""
    decision: str = ""              # CREATE | EXTEND | SKIP | "" (not drafted yet)
    summary: str = ""               # short "what / why"
    payload: str = ""               # JSON of the full compiler proposal (empty until drafted)
    status: str = "suggested"       # suggested | drafting | pending | applied | rejected | error
    created_at: dt.datetime = Field(default_factory=now)
    decided_at: Optional[dt.datetime] = None


_engine = None


def _ensure_columns(engine) -> None:
    """Add columns introduced after a table was first created (SQLite has no
    automatic migration; create_all only makes missing tables)."""
    from sqlalchemy import text
    adds = [("flashcard", "deep_explanation", "TEXT DEFAULT ''")]
    with engine.connect() as conn:
        for table, col, decl in adds:
            try:
                cols = [r[1] for r in conn.execute(text(f"PRAGMA table_info({table})"))]
                if cols and col not in cols:
                    conn.execute(text(f"ALTER TABLE {table} ADD COLUMN {col} {decl}"))
            except Exception:
                pass
        conn.commit()


def get_engine():
    global _engine
    if _engine is None:
        config.STATE_DB.parent.mkdir(parents=True, exist_ok=True)
        _engine = create_engine(
            f"sqlite:///{config.STATE_DB}",
            connect_args={"check_same_thread": False},
        )
        SQLModel.metadata.create_all(_engine)
        _ensure_columns(_engine)
    return _engine


def db() -> DBSession:
    """Open a session: `with state.db() as s: ...`."""
    return DBSession(get_engine())


def get_progress(key: str, default: str = "") -> str:
    with db() as s:
        row = s.get(Progress, key)
        return row.value if row else default


def set_progress(key: str, value: str) -> None:
    with db() as s:
        row = s.get(Progress, key)
        if row:
            row.value, row.updated_at = value, now()
        else:
            row = Progress(key=key, value=value)
        s.add(row)
        s.commit()


def record_usage(backend, model, role, input_tokens, output_tokens,
                 cache_write_tokens=0, cache_read_tokens=0, cost_usd=0.0):
    with db() as s:
        s.add(TokenUsage(
            backend=backend, model=model, role=role,
            input_tokens=input_tokens, output_tokens=output_tokens,
            cache_write_tokens=cache_write_tokens, cache_read_tokens=cache_read_tokens,
            cost_usd=cost_usd,
        ))
        s.commit()


def record_promotion(page, title, area, decision):
    with db() as s:
        s.add(Promotion(page=page, title=title, area=area, decision=decision))
        s.commit()


# ── Review queue ─────────────────────────────────────────────────────────────
def add_review_item(*, kind, title, area="", source="", decision="", summary="",
                    payload="", status="suggested", dedupe=True) -> int:
    """Insert a review item. If dedupe, skip when a non-terminal item with the same
    kind+title already exists (avoids re-queuing the same gap each audit)."""
    from sqlmodel import select
    with db() as s:
        if dedupe:
            existing = s.exec(
                select(ReviewItem).where(ReviewItem.kind == kind, ReviewItem.title == title,
                                         ReviewItem.status.in_(("suggested", "pending", "drafting")))
            ).first()
            if existing:
                return existing.id
        item = ReviewItem(kind=kind, title=title, area=area, source=source,
                          decision=decision, summary=summary, payload=payload, status=status)
        s.add(item)
        s.commit()
        s.refresh(item)
        return item.id


def list_review(status: str | None = None, limit: int = 200) -> list[ReviewItem]:
    from sqlmodel import select
    with db() as s:
        q = select(ReviewItem).order_by(ReviewItem.id.desc())
        if status:
            q = q.where(ReviewItem.status == status)
        return list(s.exec(q))[:limit]


def get_review(item_id: int) -> Optional["ReviewItem"]:
    with db() as s:
        return s.get(ReviewItem, item_id)


def update_review(item_id: int, **fields) -> None:
    with db() as s:
        item = s.get(ReviewItem, item_id)
        if not item:
            return
        for k, v in fields.items():
            setattr(item, k, v)
        if fields.get("status") in ("applied", "rejected"):
            item.decided_at = now()
        s.add(item)
        s.commit()


def review_counts() -> dict:
    from sqlmodel import select
    out = {"suggested": 0, "pending": 0, "applied": 0, "rejected": 0, "drafting": 0, "error": 0}
    with db() as s:
        for it in s.exec(select(ReviewItem)):
            out[it.status] = out.get(it.status, 0) + 1
    return out


if __name__ == "__main__":
    get_engine()
    print(f"Initialized state DB at {config.STATE_DB}")
    for tbl in SQLModel.metadata.tables:
        print(f"  table: {tbl}")
